name: Custom Command

on:
 push:
 workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  With_Command_Input:
    uses: ./.github/workflows/test.yml
    with:
      project: APP
      command: 'ls -la APP'

  Without_Command_Input:
    uses: ./.github/workflows/test.yml
    with:
      project: build