name: Tag Deployment

on:
  push:
    branches-ignore: 
      - 'main'
    tags:
      - 'v*'
      - 'staging*'
      - 'mirror-v*'
      - 'mirror-staging*'

jobs:
  Test: # This should run on push to any branch
    if: "!startsWith(github.ref, 'refs/tags/mirror-v') && !startsWith(github.ref, 'refs/tags/mirror-staging')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # test
      - name: Run tests
        run: echo "Running tests..."

  Build: # This should run on push tag v1 and staging
    if: "startsWith(github.ref, 'refs/tags/staging') || startsWith(github.ref, 'refs/tags/v')"
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Build
        run: echo "Running Build..."
# This is uat code below
  deploy-uat:
    if: startsWith(github.ref, 'refs/tags/staging')
    needs: [Test, Build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to UAT
        run: echo "Deploying to UAT..."
        
  deploy-prod:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [Test, Build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: TDB-ORG/cross-repo-update
          ref: main
      - name: Deploy to Production
        shell: bash
        run: |
          export COMMIT_HASH="${{ github.sha }}"
          export PROJECT_NAME=Test-Project
          export DEPLOYMENT_ENV=uat
          ./scripts/update-image-tag.sh
          ./scripts/commit-changes.sh

  deploy-uat-mirror:
    if: startsWith(github.ref, 'refs/tags/mirror-staging')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to UAT mirror
        run: echo "Deploying to uat mirror..."

  deploy-prod-mirror:
    if: startsWith(github.ref, 'refs/tags/mirror-v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to Poduction Mirror
        run: echo "Deploying production Mirror..."

