name: Tag Deployment

on:
  push:
    branches-ignore: 
        - 'main'
    tags:
      - 'v*'
      - 'staging*'
      - 'mirror-v*'
      - 'mirror-staging*'

jobs:
  Test: #This should run on push to any branch
    if: "!startsWith(github.ref, 'refs/tags/staging') && !startsWith(github.ref, 'refs/tags/mirror-staging')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # test
      - name: Run tests
        run: |
          echo "Running tests..."

 Build: #This should run on push tag  v1 and staging
    if: "startsWith(github.ref, 'refs/tags/staging') || startsWith(github.ref, 'refs/tags/v')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          echo "Running tests..."       
    
  deploy-prod:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy to production
        run: echo "Deploying to production..."

  deploy-uat:
    if: startsWith(github.ref, 'refs/tags/staging')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Deploy to UAT
        run: echo "Deploying to UAT..."

  deploy-prod-mirror:
    if: startsWith(github.ref, 'refs/tags/mirror-v')
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy to production
        run: echo "Deploying to production..."

  deploy-uat-mirror:
    if: startsWith(github.ref, 'refs/tags/mirror-staging')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Deploy to UAT
        run: echo "Deploying to UAT..."        
