name: Tag Deployment

on:
  push:
    branches-ignore: 
        - 'main'
    tags:
      - 'v*'
      - 'staging*'

#   pull_request:
#     branches:
#       - main

# concurrency:
#     group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#     cancel-in-progress: true

jobs:
  Test: #This should run on push to any branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # test
      - name: Run tests
        run: |
          echo "Running tests..."
    
  deploy-prod:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure on master/main
        run: |
          if [ $(git rev-parse --abbrev-ref HEAD) != "main" ]; then
            echo "Please switch to main branch"
            exit 1
          fi

      - name: Deploy to production
        run: echo "Deploying to production..."

  deploy-uat:
    if: startsWith(github.ref, 'refs/tags/staging')
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Ensure on master/main
        run: |
          if [ $(git rev-parse --abbrev-ref HEAD) != "main" ]; then
            echo "Please switch to main branch"
            exit 1
          fi

      - name: Deploy to UAT
        run: echo "Deploying to UAT..."
