name: Upload and Execute Script

on:
  push:
    branches:
      - script-runner

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Grant Execute Permission
        run: chmod +x scripts/run.sh
    
      # Step 2: Tar and upload the script as an artifact
      - name: Tar files
        run: tar -cvf my-script.tar ./scripts

      - name: Upload Script as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-script
          path: my-script.tar

  download-and-execute:
    runs-on: ubuntu-latest
    needs: upload # Add dependency on the 'upload' job

    steps:
      # Step 1: Download the artifact
      - name: Download Script Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-script
          path: ./ # Downloads the tar file to the current directory

      # Step 2: Extract the tar archive
      - name: Extract Script
        run: tar -xvf my-script.tar

      # Step 3: Execute the script
      - name: Execute the Script
        run: ./scripts/run.sh # Use the full path to the extracted script

      # Step 4: Print the output of the script
      - name: Cat output
        run: cat scripts/date_time.txt # Use the path to the output file
