name: Tag Based Deployment

on:
  workflow_dispatch:
  create:
    tags:
      - '*'

jobs:
  STAGING:
    if: contains(github.ref, 'refs/tags/staging-v')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: STAGING Deployment
        run: echo "Deploying to STAGING for ref ${{ github.ref }}"

  PROD:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: PROD Deployment
        run: echo "Deploying to PROD for ref ${{ github.ref }}"
