name: Tag Based Deployment

on:
 workflow_dispatch:
 create:
# permissions:
#   id-token: write
#   contents: write

jobs:
  STAGING:
    # # if: github.event.created.ref == 'staging-v*'
    # if: ${{ github.ref}} == 'refs/tags/staging-v.*'
    if: contains(${{ github.ref }}, 'refs/tags/staging-v')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
    - name: This STAGING #GHActions repo containing files to be edited
      run: echo "this is ${{ github.ref}}"      
  PROD:
    if: ${{ github.ref}} == 'refs/tags/v.*'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
    - name: This PROD #GHActions repo containing files to be edited
      run: echo "this is ${{ github.ref}}"
