name: Command As Input

on:
  workflow_call:
    inputs:
      project:
        required: false
        type: string
        default: ''
      command:
        description: Command to run
        required: false
        type: string
        default: ''

permissions:
  id-token: write
  contents: write

jobs:
  Command_Runner:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Clone Target Repo
      uses: actions/checkout@v4
      with:
        repository: TheDevopsBuddy/GHActions-Pocs
        ref: 'main'

    - name: Command Runner
      shell: bash
      run: |
        echo "Running command on project: ${{ inputs.project }}"
        if [ -z "${{ inputs.command }}" ]; then
          ls -la ${{ inputs.project }}
          exit 1
        else
          sh -c "${{ inputs.command }}"
        fi
