name: Commit and Push Changes

on:
  push:
    branches: [ "feat/Update-file" ]
    
# permissions:
#   id-token: write
#   contents: write

jobs:
  update-file:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
    - name: Clean up
      run: |
            rm -rf ./GHActions-Poc
            mkdir ./GHActions-Poc
    - name: Clone Target Repo #GHActions repo containing files to be edited
      uses: actions/checkout@v4
      with:
        repository: TheDevopsBuddy/GHActions-Pocs
        path: ./GHActions-Poc
        ref: 'feat/Update-file'
        #token: ${{ secrets.GITHUB_TOKEN }}
        #token: ${{ secrets.GH_PAT }}        
    - name: Bump Image Tag
      run: |
        yq e ".my-application.application.image.tag = \"test-'${{ github.sha }}'\"" -i ./GHActions-Poc/LC/values-uat.yaml
    - name: Commit and Push
      run: |
        cd ./GHActions-Poc
        git add .
        if [ -z "$(git status --porcelain)" ]; then
          echo "No changes detected."
        else
          # git config --global user.email "mangeshsuryawanshi.tdg@gmail.com"
          # git config --global  user.name "TheDevopsBuddy"
          git config --unset-all http.https://github.com/.extraheader
          git config --global user.email "dummy@jones.com"
          git config --global  user.name "Dummy Jones"          
          git commit -m "Bumping image tag to \"test-'${{ github.sha }}'\""
          git push origin feat/Update-file
        fi
