name: Workflow Dispatch POC
on:
    push:
        branches:
            - workflow_dispatch_poc
    workflow_dispatch:
jobs:
    e2e-test-hold:
      name: Approval Hold
      runs-on: ubuntu-latest
      environment: HOLD
  
  