name: CICD

on:
 push:
 workflow_dispatch:

jobs:
  var-passing:
    runs-on: ubuntu-latest
    outputs:
      variable: ${{ steps.set-env.outputs.variable }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Environment Variable
        id: set-env
        run: echo "variable=test" >> $GITHUB_OUTPUT

      - name: Variable Parser
        uses: ./.github/actions/var-parse/action.yml
        with:
          variable: ${{ steps.set-env.outputs.variable }}
