name: Workflow Dispatch POC
on:
    push:
        branches:
            - workflow_dispatch_poc
    workflow_dispatch:
jobs:
    e2e-test-hold:
      name: Approval Hold
      runs-on: ubuntu-latest
      steps:
        - name: Approval Required
          run: echo "Approval required to proceed."
          if: ${{ github.event_name == 'workflow_dispatch' }}
  