name: CICD

on:
 push:
 workflow_dispatch:

jobs:
  var-passing:
    runs-on: ubuntu-latest
    outputs:
      shortSha: ${{ steps.shortSha.outputs.short_sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Environment Variable
        id: shortSha
        run: echo short_sha=$(git rev-parse --short ${{ github.sha }}) >> $GITHUB_OUTPUT

      - name: Variable Parser
        uses: ./.github/actions/var-parse
        with:
          variable: ${{ steps.shortSha.outputs.short_sha }}
